package com.java.insurance.app.models.enums;

public enum DiseaseType {
    HEART_DISEASE, DIABETES, ASTHMA, CANCER, KIDNEY_DISEASE, LIVER_DISEASE, THYROID_DISEASE, TUBERCULOSIS, ALZHEIMER, DENTAL_CAVITIES, DENTAL_ABSCESS, ORAL_CANCER
}
