package com.java.insurance.app.models.enums;

public enum Permission {
    USER_READ, USER_WRITE, ROLE_READ, ROLE_WRITE, POLICY_READ, POLICY_WRITE, BENEFICIARY_READ, BENEFICIARY_WRITE, APPLICATION_READ, APPLICATION_WRITE, APPLICATION_CREATE
}
